language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.10
  - 2.0.0
env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=3.2.0"
branches:
  only:
    - master
    - travis